spring:
  data:
    mongodb:
      main:
        uri: ${MONGO_URI_MAIN}
      logs:
        uri: ${MONGO_URI_LOGS}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXP_MS:86400000}

server:
  port: ${PORT:8080}
