spring:
  data:
    mongodb:
      primary:
        uri: mongodb://localhost:27017/logsDB
      secondary:
        uri: mongodb://localhost:27017/metaDB

jwt:
  secret: "1234567890123456789012345678901234567890"
  expiration-ms: ${JWT_EXP_MS:86400000}

cors:
  allowed-origins:
    - http://localhost:3000

server:
  port: 8080
